config/routes.rb
Goforums::Application.routes.draw do
  
  get "topics/new"
  get "post/new"
  get "forums/home"
  get "blank" => "forums#blank"
  root 'forums#home'
  devise_for :users
  get "posts/new/(:id)" => "posts#new", :as => 'new_post'
  resources :topics
  resources :posts, :only => [:create]

  
  get "topics(/:id(/:page))" => "topics#show", :as => 'topics_page'

  

end

app/models/post.rb
# == Schema Information
#
# Table name: posts
#
#  id         :integer          not null, primary key
#  created_at :datetime
#  updated_at :datetime
#  user_id    :integer
#  posts      :text(255)
#  topic_id   :integer
#

class Post < ActiveRecord::Base
  belongs_to :user
  belongs_to :topic
end

app/models/topic.rb
# == Schema Information
#
# Table name: topics
#
#  id         :integer          not null, primary key
#  created_at :datetime
#  updated_at :datetime
#  user_id    :integer
#  title      :string(255)
#  is_sticky  :boolean
#

class Topic < ActiveRecord::Base
  has_many :posts, :dependent => :destroy
  accepts_nested_attributes_for :posts
  belongs_to :user
  
  validates :title, :presence => true
  

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  email                  :string(255)      default(""), not null
#  encrypted_password     :string(255)      default(""), not null
#  reset_password_token   :string(255)
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0)
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string(255)
#  last_sign_in_ip        :string(255)
#  created_at             :datetime
#  updated_at             :datetime
#  name                   :string(255)
#  username               :string(255)
#  is_admin               :boolean
#  image                  :string(255)
#

class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  has_many :topics
  has_many :posts
  
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :authentication_keys => [:username]
         
  validates :username, presence: true, uniqueness: true
  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  before_filter :configure_permitted_parameters, if: :devise_controller?

  
  def configure_permitted_parameters
     devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:username, :name, :email, :password, :password_confirmation) }
  end
end

app/controllers/forums_controller.rb
class ForumsController < ApplicationController
  def home
    @topics_anouncement = Topic.find(:all, :order => "created_at DESC, is_sticky")
    @topics = Topic.order("created_at DESC, is_sticky").page(params[:page]).per(5)
    
    #@topics = Topic.find(:all, :order => "created_at DESC, is_sticky").page(1).per(5)
    #@page_topics =  Topic.page(1).per(5)
    
  end
  
  def blank
    
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_filter :authenticate_user!
  
  def new
    @posts = Post.new
  end
  
  def create
   
    @posts = Post.new(posts_params)
    
    if @posts.save
      @topic = Topic.find(@posts.topic_id)
      @post_page = @topic.posts.page(params[:page]).per(10).num_pages
      redirect_to topics_page_path(@posts.topic_id, params[:page] = @post_page)
    else
      render 'new'
    end
  end
  
  private
    def posts_params
      
      params.require(:post).permit(:user_id , :posts, :topic_id)
      
    end
end

help me im in love
got rejectssed

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  before_filter :authenticate_user!, :except => :show
  
  def show
    @topics = Topic.find(params[:id])
    @posts = @topics.posts.page(params[:page]).per(10)
    @user = User.find(@topics.user_id)
  end
  
  def new
    @topics = Topic.new
    @topics.posts.build      # => build a few posts in memory for @topics
  end
  
  def create
    @topics = Topic.new(topics_params)
    
    
    if @topics.save
      
      flash[:notice] = "New post added"
      redirect_to topic_path(@topics)
    else
      render 'new'
    end
    
  end
  
  private
    def topics_params
      
      params.require(:topic).permit(:title, :user_id, posts_attributes: [:user_id, :posts])
      
    end
    
end

dfasgfggadtaegdg


featuring this branch is so thursday ago huehuehue
more features are here baby

app/helpers/application_helper.rb
module ApplicationHelper

end

app/helpers/forums_helper.rb
module ForumsHelper
  
  def lastpost_timestamp(id)
    topic = Topic.find(id)
    timestamp = topic.posts.last
    lastpost_timestamp = timestamp.created_at
  end
  
end

app/helpers/posts_helper.rb
module PostsHelper
  def username(id)
    username = User.find(id).username
  end
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/forums/blank.html.erb
<div class="pics"> 
    <img src="assets/brownies.jpg" width="200" height="200" /> 
    <img src="assets/pinkachu.png" width="200" height="200" /> 
    <img src="images/beach3.jpg" width="200" height="200" /> 
</div> 

<div class = "jscript">
	
</div>

app/views/forums/home.html.erb
<%= link_to "<span>Post new topic</span>".html_safe, topics_new_path, :id => "logo_new_topic", title: "Post New Topic", :width => 96 %><div class="paginate_top"><%= paginate @topics %></div>
<% @topics_anouncement.each do |topic| %>
	<% if topic.title == "Announcement"%>
		<div class="announcement">
		
				
				<table class="tblthreads_header">
					<tr>
						<td id="anntitle">ANNOUNCEMENT</td>
						<td id="annreplies">REPLIES</td>
						<td id="annviews">VIEWS</td>
						<td id="annlastpost">LASTPOST</td>
					</tr>
					<tr class = "threadcell">
						<td id="title"><%= link_to topic.title, topic_path(topic) %><br> by <%= topic.user.username %></td>
						<td id="replies"><%= topic.posts.count%></td>
						<td id="views">N/A</td>
						<td id="lastpost"><%= lastpost_timestamp(topic.id).strftime("%d %B %Y, %H:%M") %></td>
					</tr>			
				</table>
				
		</div>
	<% end %>

<% end %>




<div class="threads">

		
		<table class="tblthreads_header">
			<tr>
				<td id="anntitle">TITLE</td>
				<td id="annreplies">REPLIES</td>
				<td id="annviews">VIEWS</td>
				<td id="annlastpost">LASTPOST</td>
			</tr>
			
			<% @topics.each do |topic| %>
				<% if topic.title != 'Announcement' %>
					<tr class = "threadcell">
						<td id="title"><%= link_to topic.title, topic_path(topic) %><br> by <%= topic.user.username %></td>
						<td id="replies"><%= topic.posts.count%></td>
						<td id="views">N/A</td>
						<td id="lastpost">LASTPOST at <%= lastpost_timestamp(topic.id).strftime("%d %B %Y, %H:%M") %></td>
					</tr>
				<% end %>
			<% end %>
		</table>
		

</div>

<%= link_to "<span>Post new topic</span>".html_safe, topics_new_path, :id => "logo_new_topic", title: "Post New Topic", :width => 96 %><div class="paginate_bot"><%= paginate @topics %></div>

app/views/layouts/_footer.html.erb
<%= debug(params) if Rails.env.development? %>

app/views/layouts/_header.html.erb
<div class= "header">
	
		<%= link_to (image_tag "logo.png", :id=>"logo1"), root_path %>
		
		<%= image_tag "pinkachu.png", :size => "100x100", :class => "animated bounce", :id => "pinkachu" %>
		
</div>

<div class = "signin_nav">
	<nav class = "navheader">
		
		
		<% if user_signed_in? %>
			<%= image_tag "icon_ucp.gif" %><%= link_to "Avatar",  '#'%>
			<%= image_tag "icon_logout.gif" %><%= link_to "Logout",  destroy_user_session_path, :method => :delete %>
			
		<% else %>
			<%= image_tag "icon_register.gif" %><%= link_to "Register", new_user_registration_path%>
			<%= image_tag "icon_logout.gif" %><%= link_to "Login",  new_user_session_path %>
		<% end %>
	</nav>
</div>

app/views/layouts/_theme.html.erb
		<table class="threadcell">
			<tr>
				<td id="title">ANNOUNCEMENT</td>
				<td id="replies">REPLIES</td>
				<td id="views">VIEWS</td>
				<td id="lastpost">LASTPOST</td>
			</tr>
		</div>
	

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Goforums</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "jquerycycle", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body onkeypress="myFunction(event)">
	<div class="container">
		<%= render 'layouts/header'%>
			
		<% flash.each do |key, value|%>
			<div class="flash <%= key %>"><%= value %></div>
		<% end %>
		
		<%= yield %>
		<%= render 'layouts/footer'%>
	</div>
	
</body>
</html>

app/views/posts/new.html.erb
<div class="signup_container">
	<div class = "signup_contents">

		<%= form_for @posts do |post|%>
			
			<%= post.label :posts %><br />
			<%= post.text_area :posts, :autofocus => true, :size => "50x10", :class => 'tinymce' %><br /><br/>
			<%= post.hidden_field :user_id, :value => current_user.id %>
			<%= post.hidden_field :topic_id, :value => params[:id] %>
			<%= submit_tag "Post" %>
		<% end %>
			
	</div>
</div>

<%= tinymce :alternate %>

					<%#= post_form.hidden_field :user_id, :value => current_user.id %><br /><br/>

app/views/topics/new.html.erb
<div class="signup_container">
	<div class = "signup_contents">

		<%= form_for @topics do |topic|%>
			
			<%= topic.label :title%><br />
			<%= topic.text_field :title, :autofocus => true %><br /><br/>
			<%= topic.hidden_field :user_id, :value => current_user.id %><br />
			
			
			
				<%= topic.fields_for :posts do |builder| %>
					<%= builder.label :posts %><br />
					<%= builder.text_area :posts, class: 'tinymce' %><br /><br/>
					<%= builder.hidden_field :user_id, :value => current_user.id %><br />
				<% end %>
				
			<%= submit_tag "Post" %>
		<% end %>
			
	</div>
</div>

<%= tinymce :alternate %>

					<%#= post_form.hidden_field :user_id, :value => current_user.id %><br /><br/>

app/views/topics/show.html.erb
<%= link_to "<span>Post a reply</span>".html_safe, new_post_path(params[:id]), :id => "logo_reply", title: "Post a reply", :width => 96 %><div class="paginate_top"><%= paginate @posts %></div>

<% @posts.each do |post|%>
	<div class = "post_container">
		
			<div class = "vertical">
				<%= username(post.user_id) %>
			</div>
		<div class = "post_content">
			Reply on: <%= post.created_at.strftime("%d %B %Y, %H:%M")%><br /><br />
			
			<p>
				<%= post.posts.html_safe %>
			</p>
				
		
		</div>
		
	</div>

<% end %>

<%= link_to "<span>Post a reply</span>".html_safe, new_post_path(params[:id]), :id => "logo_reply", title: "Post a reply", :width => 96 %><div class="paginate_bot"><%= paginate @posts %></div>